Задание 1: архитектура интерпретатора командной строки
GlebSolovev/SD-2022-ezh pull request #1
Opened 2022-01-24 05:09 UTC by GlebSolovev

На автоматы действительно ушло *очень* много времени...

2022-01-25 14:21 UTC, yurii-litvinov requested changes
Ещё комментарии по диаграммам:
- вы как-то сразу привязываете реализацию к Котлину, хотя архитектуру стоит делать языконезависимой по возможности
- с автоматами вы и вправду перестарались, в хорошем смысле --- это сильно поможет в реализации. Хотя есть подозрение, что можно было как-то проще (например, выполнять подстановку сразу при лексинге, но не уверен)

Но вообще, на самом деле очень круто. Надо пару небольших уточнений, и будет зачтена.

2022-01-25 14:21 UTC, yurii-litvinov commented on ARCHITECTURE.md
> +Объект класса `Environment` является же хранилищем контекста сессии, т. е. глобальных перемен. Хранение и интерфейс интуитивны: переменные хранятся в изменяемой `MutableMap`, действующей из `WORD` в
```suggestion
Объект класса `Environment` является же хранилищем контекста сессии, т. е. глобальных переменных. Хранение и интерфейс интуитивны: переменные хранятся в изменяемой `MutableMap`, действующей из `WORD` в `WORD`, где `WORD` &mdash; это класс токена слова, хранящий внутри строку, про них подробнее см. далее (после экспериментов с командной строкой Bash было выявлено, что в переменных хранятся именно строки, поэтому мы приняли аналогичное логичное решение). Доступ к ней и модификация происходят через методы `getVariable` и `putVariable`. Исключения данные методы не вызывают (так как чтение отсутствующей ранее переменной &mdash; это пустая строка аналогично поведению Bash-а), количество глобальных переменных отдельно кроме как размером памяти никак не ограничивается.
```

И "аналогичное логичное решение" звучит странно, доверьте читателю судить, логичное оно или нет

2022-01-25 14:21 UTC, yurii-litvinov commented on ARCHITECTURE.md
> +Вернемся к методу `lex`. Его цель: определить конец ввода пользователя (так как в будущем это могут быть не просто спец. символы вроде переноса строки, но и специальные ключевые слова и т. д.), разоб
Вообще, кажется, что "в будущем" --- это уже признак овердизайна, тем более что тут делаются довольно необычные предположения о том, как в будущем будет организован пользовательский ввод. Тут ладно, но в реальной жизни стоит сделать максимально просто, чтобы в будущем, если будет реально надо, было легко разобраться в существующем коде, зарефакторить, и реализовать новую функциональность. Вы же тут, даже если будущее оправдает ваши ожидания, запутаетесь в обобщениях кода лексера и не сможете ничего сделать :)

2022-01-25 14:21 UTC, yurii-litvinov commented on ARCHITECTURE.md
> +Вернемся к методу `lex`. Его цель: определить конец ввода пользователя (так как в будущем это могут быть не просто спец. символы вроде переноса строки, но и специальные ключевые слова и т. д.), разоб
И опять, "отлично обоснованное разделение обязанностей" звучит как "наш замечательный шелл", даже если вы не это имели в виду. В технических текстах надо избегать оценочных суждений.

2022-01-25 14:21 UTC, yurii-litvinov commented on ARCHITECTURE.md
> +* `SUBST` &mdash; имя переменной, вместо которого необходимо подставить ее значение; причем переменная находится не в окружении кавычек (это влияет на интерпретация пробелов после подстановки, см. да
```suggestion
* `SUBST` &mdash; имя переменной, вместо которого необходимо подставить ее значение; причем переменная находится не в окружении кавычек (это влияет на интерпретацию пробелов после подстановки, см. далее);
```

2022-01-25 14:21 UTC, yurii-litvinov commented on ARCHITECTURE.md
> +* `QSUBST` &mdash; аналог `SUBST`, но уже в окружении двойных кавычек (в данном случае пробелы в подстановке не будут разбивать подставленную строку по пробелам).
Мм, выражение вида "a $x bc" должно распарситься, с одной стороны в WORD (потому что это одно слово), с другой стороны в QSUBST и, видимо, ещё что-то (два WORD)? Непонятно, так что стоит тут пояснить.

2022-01-25 14:21 UTC, yurii-litvinov commented on ARCHITECTURE.md
> +* Затем аналогичным образом выполняется замена `SUBST` на строки-значения их переменных. Однако в данном случае строки-значения проходят процесс разбиения на `WORD`-ы и `SPACE`-ы, на которые уже в ре
Да, это хорошо, но это тот же код, что был в лексере, или какой-то отдельный? И, наверное, разбиению по WORD-ам подвергаются не только результаты подстановки, но и контекст (например, `x=b ... a$x` даст один WORD `ab`).

2022-01-25 14:21 UTC, yurii-litvinov commented on ARCHITECTURE.md
> +   * единственная операция без пайпов (соответствует размеру списка токенов длины 1);
1? У операции же могут быть аргументы, которые отдельные токены после лексера, или тут не про то?

2022-01-25 14:21 UTC, yurii-litvinov commented on ARCHITECTURE.md
> +* наследники класса `Command` бывают двух типов: реализованные нашим приложением команды (`PwdCommand` для pwd, `EchoCommand` для echo и так далее) и остальные, которые предполагаются внешними, им со
Ну, отличать-то не штука, для этого классы не нужны. Наверное, важно то, что у них execute отличается

2022-01-25 14:21 UTC, yurii-litvinov commented on ARCHITECTURE.md
> +* после долгих экспериментов с Bash мы пришли к выводу, что присваивания переменных в пайпах работают неинтуитивно (и на деле вообще не работают) &mdash; в нашей же программе мы выбрали наглядную лог
Справедливости ради пайпы в bash работают параллельно, так что семантика присваивания в этом случае сама по себе неочевидна. Поскольку у вас пайпы последовательные, вы, конечно, можете сделать разумнее, чем bash (но не потому что bash плохой, он другой просто).

2022-01-25 14:21 UTC, yurii-litvinov commented on ARCHITECTURE.md
> +* если `Exit` &mdash; перейти к последнему пункту, после чего бросить специальное исключение, сигнализирующее `Ezh` о необходимости завершить программу;
Это идеологически плохо, исключения всё-таки для обработки ошибок. У вас так или иначе есть состояние шелла (тот же Env), можно туда добавить флаг "всё, надо закончить" и проверять его при исполнении пайпа. Тем более что в будущем в этом же состоянии может оказаться текущая директория, которую можно будет менять командой cd

2022-01-25 14:21 UTC, yurii-litvinov commented on ARCHITECTURE.md
> +  * новый поток &mdash; имеется в виду новый / второй сейчас неиспользуемый временный файл (понятное дело, на весь пайп достаточно двух временных файлов);
Прямо настоящие файлы в файловой системе --- кажется, это оверкилл. Есть системные пайпы или именованные пайпы (fifo-очереди), которые живут в оперативной памяти (кстати, они вроде даже в Windows есть), да просто байтовые массивы для ввода-вывода тоже могут быть ок (раз уж у вас всё последовательно, так что чтение-запись можно не синхронизировать). Если вывод команды не лезет в оперативку, то дела и так плохи, зато если лезет, будет работать гораздо быстрее.

2022-01-29 17:30 UTC, GlebSolovev commented on ARCHITECTURE.md
> +Объект класса `Environment` является же хранилищем контекста сессии, т. е. глобальных перемен. Хранение и интерфейс интуитивны: переменные хранятся в изменяемой `MutableMap`, действующей из `WORD` в
"поэтому мы приняли аналогичное логичное решение" &mdash; хотелось подвести итог прошлой мысли, т. е. подчеркнуть, что она служит объяснением принятия решения. Вообще мы немного увлеклись за данным занятием, и явные фразы, подчеркивающие, что мы объясняем наши выборы, в архитектурной документации &mdash; лишние. Так что резонно их убираем!

А еще "аналогичное логичное" было ситуативной словесной шуткой :)

2022-01-29 17:33 UTC, GlebSolovev commented on ARCHITECTURE.md
> +Вернемся к методу `lex`. Его цель: определить конец ввода пользователя (так как в будущем это могут быть не просто спец. символы вроде переноса строки, но и специальные ключевые слова и т. д.), разоб
Принято! Про оценочное суждение аналогично "аналогичному логичному" выше, исправили.

2022-01-29 17:42 UTC, GlebSolovev commented on ARCHITECTURE.md
> +* `QSUBST` &mdash; аналог `SUBST`, но уже в окружении двойных кавычек (в данном случае пробелы в подстановке не будут разбивать подставленную строку по пробелам).
Выражение "a $x bc" лексером разобъется в `WORD, QSUBST, WORD` &mdash; и как раз потому что между данными токенами нет `SPACE`-ов, на втором этапе лексинга после посдтановок все это счастье соберется в один `WORD`.

В документе с архитектурой супер-подробно это текстом не прописывали, так как рядом с ней идут слайды с автоматом &mdash; на которых четко разбираются детали. В тексте лишь пояснили общую суть каждого токена, которую дальше частично отразили в примере.

2022-01-29 17:56 UTC, GlebSolovev commented on ARCHITECTURE.md
> +* Затем аналогичным образом выполняется замена `SUBST` на строки-значения их переменных. Однако в данном случае строки-значения проходят процесс разбиения на `WORD`-ы и `SPACE`-ы, на которые уже в ре
Это второй этап лексинга, который реализует второй метод того же самого Lexer-а &mdash; все разбиение на лексемы зашито в нем. 

Разбиение же на пробелы не является переиспользуемым куском &mdash; в случае первого этапа лексинга он является частью автомата со своими особенностями в разных состояниях. Поэтому в отдельный приватный метод, конечно, разбиение на пробелы для второго этапа лексинга будет вынесено, но в первом этапе переиспользовано не будет. Так можно будет отдельно и безболезненно понимать код двух методов.

И верно, что на `WORD`-ы и прочие лексемы разбивать нужно не только подставляемые строки mdash; разбиение контекста происходит на первом этапе лексинга.

2022-01-29 18:02 UTC, GlebSolovev commented on ARCHITECTURE.md
> +   * единственная операция без пайпов (соответствует размеру списка токенов длины 1);
Имелся в виду список операций, передаваемый уже `Parser`-ом `Execetor`-у. И тогда уже этот комментарий ставновится чистой воды тавтологией, исправляем!

2022-01-29 18:02 UTC, GlebSolovev commented on ARCHITECTURE.md
> +   * единственная операция без пайпов (соответствует размеру списка токенов длины 1);
Имелся в виду список операций, передаваемый уже `Parser`-ом `Executor`-у. И тогда уже этот комментарий ставновится чистой воды тавтологией, исправляем!

2022-01-29 18:14 UTC, GlebSolovev commented on ARCHITECTURE.md
> +* наследники класса `Command` бывают двух типов: реализованные нашим приложением команды (`PwdCommand` для pwd, `EchoCommand` для echo и так далее) и остальные, которые предполагаются внешними, им со
Да, конечно, разница в `execute`: `PwdCommand`, `EchoCommand`, `EchoCommand` &mdash; каждый по-своему. Однако в тексте хотелось объяснить, почему было недостаточно одного класса, который умеет вызывать просто какую-то команду извне &mdash; не видя разницы между знакомым нашему приложению `pwd` и незнакомой командой. Текст поправили.

2022-01-29 18:58 UTC, GlebSolovev commented on ARCHITECTURE.md
> +* если `Exit` &mdash; перейти к последнему пункту, после чего бросить специальное исключение, сигнализирующее `Ezh` о необходимости завершить программу;
Да, на исключениях действительно плохо. А идея добавить в `Environment` поле для статуса отличная: и идейно логично, и хорошо с точки зрения кода. При этом бонусом `exit` в конце пайпа начинает работать так же, как и в Bash-е (правда, по другим причинам), завершая собой пайп, а не всю сессию, так как локально модифицированный в пайпе контекст мы к глобальному не добавляем. Исправили в тексте и в схеме.

2022-01-29 19:48 UTC, GlebSolovev commented on ARCHITECTURE.md
> +  * новый поток &mdash; имеется в виду новый / второй сейчас неиспользуемый временный файл (понятное дело, на весь пайп достаточно двух временных файлов);
Все так! Про файлы идея была только потому, что сначала хотели использовать стандартный `ProcessBuilder`, который умеет перенаправлять потоки только через `File`. Однако уже нашли идеальное решение: https://github.com/fleipold/jproc, так что теперь честно, красиво и просто будем работать с потоками :) Исправили и в тексте, и в схеме.

2022-01-29 19:52 UTC, GlebSolovev commented
> вы как-то сразу привязываете реализацию к Котлину, хотя архитектуру стоит делать языконезависимой по возможности

Согласны! Просто нужен был какой-то язык для единообразия, так как собираемся писать на котлине &mdash; для удобства выбрали его. Вроде бы он один из самых читаемых :)

2022-01-29 19:53 UTC, GlebSolovev commented
> вы как-то сразу привязываете реализацию к Котлину, хотя архитектуру стоит делать языконезависимой по возможности

Согласны! Просто нужен был какой-то язык для единообразия, так как собираемся писать на Котлине &mdash; для удобства выбрали его. Вроде бы он один из самых читаемых :)

2022-01-30 16:45 UTC, yurii-litvinov approved these changes
Всё круто, существенных замечаний не осталось. Зачтена.

2022-01-30 16:45 UTC, yurii-litvinov commented on ARCHITECTURE.md
> +* `QSUBST` &mdash; аналог `SUBST`, но уже в окружении двойных кавычек (в данном случае пробелы в подстановке не будут разбивать подставленную строку по пробелам).
Ну, да, но в тексте это таки вызвало удивление, стоило пояснить

2022-01-30 16:45 UTC, yurii-litvinov commented on ARCHITECTURE.md
> +Наконец, `View` является интерфейсом по следующей причине: в будущем, возможно, захочется поддержать различные источники и точки выхода данных программы; например, чтение из файла / запись в него; по
"интерп**рет**атором" :)

2022-01-30 16:45 UTC, yurii-litvinov commented on ARCHITECTURE.md
> +* Затем аналогичным образом выполняется замена `SUBST` на строки-значения их переменных. Однако в данном случае строки-значения проходят процесс разбиения на `WORD`-ы и `SPACE`-ы, на которые уже в ре
Ага, окей.

2022-02-04 14:29 UTC, closed without merging