Задание 3: реализация интерпретатора командной строки, часть 2
GlebSolovev/SD-2022-ezh pull request #4
Opened 2022-02-12 22:38 UTC by GlebSolovev

**Авторы: Денис Лочмелис, Глеб Соловьев**

В этот раз потребовалось уже меньше времени, так как вся красота была настроена :)

2022-02-21 12:56 UTC, yurii-litvinov requested changes
Что-то не то, видимо, с пробелами и пайпами:
```
echo 123 | wc
2       1       4
echo 123 | cat | wc
3       1       5
echo 123 | cat | cat | wc
4       1       6
```
Настоящий bash выдаёт `1 1 4`, и результаты, конечно, не меняются от пайпа в cat-ы.

В остальном всё хорошо.

2022-02-23 15:16 UTC, DLochmelis33 commented
Дело в том, что все наши команды печатают в конце `\n`, и за счет это растет кол-во строк и кол-во байт. Вероятно, было бы логичнее сделать так, чтобы этот перенос добавлялся только в `ConsoleView`...

2022-02-27 10:25 UTC, yurii-litvinov commented
Конечно. Если к произвольным бинарным данным добавлять `\n` и скармливать их дальше командам в пайпе, беда неизбежна. Это чисто UI-шная функциональность. Поправьте, пожалуйста.

2022-02-27 18:30 UTC, GlebSolovev commented
> Что-то не то, видимо, с пробелами и пайпами:
> 
> ```
> echo 123 | wc
> 2       1       4
> echo 123 | cat | wc
> 3       1       5
> echo 123 | cat | cat | wc
> 4       1       6
> ```
> 
> Настоящий bash выдаёт `1 1 4`, и результаты, конечно, не меняются от пайпа в cat-ы.
> 
> В остальном всё хорошо.

Все верно, наша исходная недодумка с `\n`-ами в выводе команд таковой и являлась &mdash; теперь устранена, переводом строки в конце вывода теперь занимается `ConsoleView`, как и положено.

*Небольшой комментарий:* теперь `\n`-а в выводе лишилась и `echo` (что отличается от стандартного поведения Bash, но разработчики Ezh-а могут себе такое позволить), поэтому:
```bash
> echo 123 | wc
> 1 1 3
```
аналогичное даже есть в тестах.

2022-02-27 19:27 UTC, yurii-litvinov approved these changes
👍

2022-02-27 21:47 UTC, closed without merging