Задание 4: реализация grep и UML диаграмма
GlebSolovev/SD-2022-ezh pull request #5
Opened 2022-02-20 11:28 UTC by GlebSolovev

**Авторы: Денис Лочмелис, Глеб Соловьев**

Кроме непосредственно требуемого в задании по причине душевного порыва добавили красивый префикс у строк в интерпретаторе :)

2022-02-20 20:03 UTC, yurii-litvinov requested changes
По диаграмме:
- множественность `1` у ассоциаций подразумевается по умолчанию, поэтому обычно не указывается, чтобы не загромождать диаграмму. Однако как у вас --- тоже можно
- `Use` пишется как `<<use>>`, это стереотип, модифицирующий тип связи dependency. Все стереотипы в UML пишутся в двойных угловых скобках (это как аннотации в Java, которые пишутся с `@`)

В остальном с диаграммой всё правильно.

2022-02-20 20:03 UTC, yurii-litvinov commented on src/main/kotlin/ru/hse/ezh/execution/commands/ExitCommand.kt
> +        INVALID_STATUS_CODE(2),
Как-то громоздко, но стало более читаемо вроде.

2022-02-20 20:03 UTC, yurii-litvinov commented on ARCHITECTURE.md
> +* наконец, [Clikt](https://ajalt.github.io/clikt/) &mdash; 100% Kotlin библиотека, выпущенная после двух вышеупомянутых; имеет лаконичный интерфейс с говорящими названиями методов, предоставляет возм
Это, конечно, придирка, но стоит ещё кратко описывать методику поиска. Если я завтра найду какой-нить СуперCLI, я должен понимать, что, например, у него меньше звёзд на GitHub, так что нечего его и смотреть, а не что вы его пропустили. Сейчас можно не править, но, например, при написании текста диплома могут прикопаться.

2022-02-20 20:03 UTC, yurii-litvinov commented on src/main/kotlin/ru/hse/ezh/views/ConsoleView.kt
> +                        print(ansiPurple + multilinePrefix + ansiReset)
Это выглядит не так хорошо с `--console=plain` :) Поэтому я бы в целом рекомендовал не извращаться и не закладываться на возможности консоли, особенно в таких низкоуровневых штуках, как шеллы. Но, конечно, исправлять не надо, оставьте.

2022-02-20 20:03 UTC, yurii-litvinov commented on src/main/kotlin/ru/hse/ezh/execution/commands/GrepCommand.kt
> +class GrepCommand(args: List<String>) : Command(args) {
Кажется, вы его забыли записать в knownCommands, так что он пытается запуститься как внешняя программа :)

2022-02-28 06:56 UTC, GlebSolovev commented on src/main/kotlin/ru/hse/ezh/views/ConsoleView.kt
> +                        print(ansiPurple + multilinePrefix + ansiReset)
Верно, судя по документации Gradle этот флаг правильного отображения цветов не гарантирует (зато на Ubuntu все равно работает 🙂). А при других значениях выводит лишние полоски прогресса... Так или иначе даже в `README.md` мы не рекомендуем таким образом приложение запускать, а в случае запуска jar-ника все будет в большинстве случаев красивее &mdash; идея добавить цвета родилась как раз при просмотре сплошникового белого полотна текста, запускать Ezh-а руками стало удобнее 🌈 !  

Но, конечно, возможны и печальные случаи неподдерживаемых цветов &mdash; замечание понятно.

2022-02-28 06:57 UTC, GlebSolovev commented on src/main/kotlin/ru/hse/ezh/execution/commands/GrepCommand.kt
> +class GrepCommand(args: List<String>) : Command(args) {
Все так... Исправили и накинули тестов, так что теперь точно все ок.

2022-02-28 09:26 UTC, yurii-litvinov approved these changes
Да, теперь всё хорошо, зачтена

2022-02-28 09:26 UTC, yurii-litvinov commented on ARCHITECTURE.md
> +*Метод поиска библиотек:* просмотрели первую страницу выдачи в Google, вспомнили уже использованные в прошлых проектах технологии; качество проектов валидировали в том числе по количеству звезд на Gi
И если уж совсем по-хорошему, стоит уточнить, что значит "качество проектов валидировали в том числе по количеству звезд на Github" (например, "проекты с числом звёзд меньше N не рассматривались" — но тогда будет закономерный вопрос, как быть с новыми хорошими проектами, которые пока просто не успели набрать звёзды)

2022-02-28 09:26 UTC, yurii-litvinov commented on ARCHITECTURE.md
> +* так и идеологическим (лаконичность и читаемость кода, популярность библиотеки, современность, полезный в будущем дополнительный функционал) потребностям.
Нуу, если результаты выбора были предрешены ещё до начала выбора, то это ну такое :)

2022-03-03 15:20 UTC, GlebSolovev commented on ARCHITECTURE.md
> +*Метод поиска библиотек:* просмотрели первую страницу выдачи в Google, вспомнили уже использованные в прошлых проектах технологии; качество проектов валидировали в том числе по количеству звезд на Gi
Использовали именно такую формлировку, так как мы не руководствовались строгим правилом "смотрим только >= такого-то числа звезд". Мы принимали решение взвешенно; количество звезд проекта могло лишь повысить или понизить доверие к тому или иному кандидату.

> Как быть с новыми хорошими проектами

Мы смотрели не только на звезды, поэтому имели шанс рассмотреть и их. Однако в методологии мы сказали: посмотрели на первую страницу Google и вспомнили, что уже использовали `(*)`. Если кто-то скажет, что мы что-то не нашли, окей. Этого не было в `(*)`, либо оно проиграло `Clikt`-у.

2022-03-03 15:24 UTC, GlebSolovev commented on ARCHITECTURE.md
> +* так и идеологическим (лаконичность и читаемость кода, популярность библиотеки, современность, полезный в будущем дополнительный функционал) потребностям.
Как раз нет! Проекты перечислены в точности в том порядке, в котором мы их изучали. И мы как раз осознанно и планомерно перебирали варианты, пока не нашли тот, который удовлетворял нашим требованиям с головой. В ситуации, когда время ограничено самое верное решение  &mdash; остановиться: супер хороший вариант найден, перебрано достаточно много аналогов для уверенности в том, что выбранный вариант действительно мощный и хороший.

2022-03-21 02:47 UTC, closed without merging